# dbt project configuration for the Synology BI platform
name: "synology_bi"
version: "1.0.0"
config-version: 2

profile: "synology_bi"

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  synosales_sources:
    - ["synology_ingestion", "2023_c2", "2023-C2"]
    - ["synology_ingestion", "seed_sales_2023", "2023"]
    - ["synology_ingestion", "2024_c2", "2024-C2"]
    - ["synology_ingestion", "seed_sales_2024", "2024"]
  synosales_suite_a_sources:
    - ["synology_ingestion", "seed_sales_2023", "2023"]
    - ["synology_ingestion", "seed_sales_2024", "2024"]
  synosales_suite_b_sources:
    - ["synology_ingestion", "2023_c2", "2023-C2"]
    - ["synology_ingestion", "2024_c2", "2024-C2"]

target-path: "target"
clean-targets:
  - "target"
  - "target_runtime"
  - "dbt_packages"

models:
  synology_bi:
    +materialized: view
    staging:
      +schema: staging
      +tags: ["staging"]
    marts:
      +schema: marts
      +tags: ["marts"]

seeds:
  synology_bi:
    +schema: seeds
    synology_ingestion:
      "2023":
        alias: seed_sales_2023
      "2024":
        alias: seed_sales_2024
